jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Prepare actions
        uses: ./.github/actions/prepare
      - name: Sync astro
        run: yarn astro sync
      - name: Linting
        run: yarn lint
      - uses: mshick/add-pr-comment@v2
        if: failure()
        with:
          message-failure: |
            Uh oh! ESLint found some issues. Please run `yarn fix` and commit the changes.

name: Lint

on:
  pull_request: ~
  merge_group: ~

  push:
    branches:
      - main
