jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Prepare actions
        uses: ./.github/actions/prepare
      - name: Prettier
        run: yarn fmt --check --write=false

name: Prettier

on:
  pull_request: ~
  merge_group: ~

  push:
    branches:
      - main
